feat: add data source for VM hosts
maas/terraform-provider-maas pull request #147
Opened 2024-01-24 20:34 UTC by skatsaounis

resolves: #122

2024-01-24 20:43 UTC, sparkiegeek requested changes

2024-01-24 20:43 UTC, sparkiegeek commented on maas/data_source_maas_vm_host.go
> +	if powerAddress, ok := vmHostParameters["password"]; ok {
```suggestion
	if powerPassword, ok := vmHostParameters["password"]; ok {
```

2024-01-24 20:43 UTC, sparkiegeek commented on maas/data_source_maas_vm_host.go
> +	if powerAddress, ok := vmHostParameters["password"]; ok {
and so on for all the other locals..

2024-06-12 10:42 UTC, closed without merging

2024-06-12 10:42 UTC, skatsaounis commented
Closed in favor of #181